/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_trzpiot_bulbbattle_service_NativeService */

#ifndef _Included_de_trzpiot_bulbbattle_service_NativeService
#define _Included_de_trzpiot_bulbbattle_service_NativeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    switchOn
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_switchOn
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    switchOff
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_switchOff
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    setColor
 * Signature: (Ljava/lang/String;Ljava/lang/String;JIII)V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_setColor
  (JNIEnv *, jobject, jstring, jstring, jlong, jint, jint, jint);

/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    setBrightness
 * Signature: (Ljava/lang/String;Ljava/lang/String;JI)V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_setBrightness
  (JNIEnv *, jobject, jstring, jstring, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
