/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_trzpiot_bulbbattle_service_NativeService */

#ifndef _Included_de_trzpiot_bulbbattle_service_NativeService
#define _Included_de_trzpiot_bulbbattle_service_NativeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    roundPause
 * Signature: (Ljava/lang/Long;)V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_roundPause
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    roundStart
 * Signature: (Ljava/lang/String;Ljava/lang/Long;)V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_roundStart
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    gamePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_gamePause
  (JNIEnv *, jobject);

/*
 * Class:     de_trzpiot_bulbbattle_service_NativeService
 * Method:    gameStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_trzpiot_bulbbattle_service_NativeService_gameStart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
